### ISSUE TITLE
Bug reading folders

### ISSUE THREAD

**Issue by emwtur** [QBNK/qbank3api-dotnetwrapper#5]
folderresponse.cs

  /// <summary>
        /// The saved search of the (filter-)folder.
        /// </summary>
        public List< SavedSearch > SavedSearch { get; set; }

**Comment by bohemima** [comment]
Hi,

I'm unsure what you are referring to here, the current implementation;

`public SavedSearch SavedSearch { get; set; }` is correct, now, the exact return value here will be a object with one property `Search` which will contain a JSON representation of a Search. If this is valuable or not is debatable but we have no plans to let it return a complete Search model as of now. It will have to be created by code for now.

**Comment by emwtur** [comment]
json comes out as:

 "savedSearch": [] ,
- thats an array/list to me !
- and the function crashes when it is parsed

**Comment by bohemima** [comment]
Hi,

What QBank instance and folderId is this?

It should come out as either;

```
"savedSearch": {
      "id": 1,
      "created": {
        "date": "2018-01-11 14:08:12.657133",
        "timezone_type": 1,
        "timezone": "+01:00"
      },
      "createdby": null,
      "search": "{\"fileSizeCriteria\":[{\"extra\":\"mb\",\"operator\":\"gt\",\"value\":10485760}]}"
    },
```

or simply `"savedSearch": null` if that specific folder does not have a saved search connected.

**Comment by emwtur** [comment]
searching root via swagger or api

**Comment by bohemima** [comment]
Alright, this instance is not updated regularly and does not have our changes for the .NET wrapper incorporated yet. Next planned update would be on February 6th. In the mean time you can remove or change this property manually.
